# Dependencies
highlighter:      rouge

# Permalinks
permalink:        pretty
relative_permalinks: false

# Setup
title:            Silas Bergen
tagline:          Course web page
description:      Course web page and resources
url:              http://hyde.getpoole.com
baseurl:          https://silasbergen.github.io/hyde/

author:
  name:           'Mark Otto'
  url:            https://twitter.com/mdo

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/silasbergen/hyde/
